### ISSUE TITLE
Candidates

### ISSUE THREAD

**Issue by gruhn** [gruhn/awesome-naming#5]
A place to quickly drop (and discuss) candidates once they come to mind so you don't forget about them.

**Comment by gruhn** [comment]
https://en.wikipedia.org/wiki/NOP_slide
https://en.wikipedia.org/wiki/Air_gap_(networking)

**Comment by danielkatz** [comment]
Israeli Queue - https://rapidapi.com/blog/israeli-queues-exploring-a-bizarre-data-structure/

**Comment by mfkaptan** [comment]
How about some of the code smells?
- Shotgun surgery
- Inappropriate intimacy
- Feature Envy
- Primitive Obsession
- Middle Man
- Refused Bequest

Also maybe some of the cyber attacks:
- Phising
- Malware / ransomware
- Poisoning (ARP)
- Smurf attack
- Ping flood (also "Ping" itself)

**Comment by thiagodp** [comment]
[SOLID](https://en.wikipedia.org/wiki/SOLID) principles

**Comment by gruhn** [comment]
the functions: explode/implode 

https://www.c-sharpcorner.com/UploadFile/051e29/implode-and-explode-function-in-php/

**Comment by gruhn** [comment]
PostgREST: https://github.com/PostgREST/postgrest

**Comment by antonk52** [comment]
[bootstrap](https://getbootstrap.com/) - css library which helps to jump start the UI part of a project.

**Comment by KubaJastrz** [comment]
[Hero image](https://en.wikipedia.org/wiki/Hero_image) - large image often placed at the top of the website
